/**
 ******************************************************************************
 * Xenia : Xbox 360 Emulator Research Project                                 *
 ******************************************************************************
 * Copyright 2022 Ben Vanik. All rights reserved.                             *
 * Released under the BSD license - see LICENSE in the root for more details. *
 ******************************************************************************
 */

#include "xenia/app/emulator_window.h"

#include <cstdlib>
#include <fstream>
#include <sstream>
#include <thread>

#include <QCursor>
#include <QGridLayout>
#include <QMenu>
#include <QMessageBox>
#include <QTimer>

#include "third_party/imgui/imgui.h"
#include "third_party/stb/stb_image_write.h"
#include "third_party/tomlplusplus/toml.hpp"
#include "xenia/base/assert.h"
#include "xenia/base/clock.h"
#include "xenia/base/cvar.h"
#include "xenia/base/debugging.h"
#include "xenia/base/filesystem.h"
#include "xenia/base/logging.h"
#include "xenia/base/platform.h"
#include "xenia/base/profiling.h"
#include "xenia/base/system.h"
#include "xenia/base/threading.h"
#include "xenia/config.h"
#include "xenia/ui/config_dialog_qt.h"
#include "xenia/ui/game_list_dialog_qt.h"
#include "xenia/ui/imgui_confirm_dialog.h"
#include "xenia/ui/imgui_context_menu.h"
#include "xenia/ui/imgui_performance_dialog.h"
#include "xenia/ui/imgui_postprocessing_dialog.h"
#include "xenia/ui/imgui_xmp_dialog.h"
#include "xenia/ui/profile_dialogs.h"
#include "xenia/ui/qt_util.h"
#include "xenia/ui/simple_config_dialog_qt.h"
#include "xenia/vfs/devices/disc_zarchive_device.h"
#include "xenia/vfs/devices/xcontent_container_device.h"

#if XE_PLATFORM_WIN32
#include <windows.h>
#else
#include <signal.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <unistd.h>
#endif

#if XE_PLATFORM_LINUX
#include <errno.h>
#include <fcntl.h>
#include <string.h>
#include <sys/stat.h>
// X11 headers
#include <X11/Xatom.h>
#include <X11/Xlib.h>
#include <X11/Xutil.h>
#include <X11/extensions/XTest.h>
#include <X11/keysym.h>
// Undefine X11 macros that conflict with our code
#ifdef None
#undef None
#endif

#ifdef Success
#undef Success
#endif
#ifdef CursorShape
#undef CursorShape
#endif
#ifdef Status
#undef Status
#endif
#ifdef Bool
#undef Bool
#endif
// Undefine X11 macros that conflict with Qt's QEvent enum
#ifdef KeyPress
#undef KeyPress
#endif
#ifdef KeyRelease
#undef KeyRelease
#endif
#ifdef FocusIn
#undef FocusIn
#endif
#ifdef FocusOut
#undef FocusOut
#endif
#ifdef FontChange
#undef FontChange
#endif
#ifdef Expose
#undef Expose
#endif
#endif

#include "xenia/cpu/processor.h"
#include "xenia/emulator.h"
#include "xenia/gpu/command_processor.h"
#include "xenia/gpu/graphics_system.h"
#include "xenia/hid/input_system.h"
#include "xenia/kernel/user_module.h"
#include "xenia/kernel/xam/profile_manager.h"
#include "xenia/kernel/xam/xam_module.h"
#include "xenia/kernel/xam/xam_state.h"
#include "xenia/ui/content_install_dialog_qt.h"
#include "xenia/ui/file_picker.h"
#include "xenia/ui/graphics_provider.h"
#include "xenia/ui/imgui_dialog.h"
#include "xenia/ui/imgui_drawer.h"
#include "xenia/ui/imgui_host_notification.h"
#include "xenia/ui/immediate_drawer.h"
#include "xenia/ui/presenter.h"
#include "xenia/ui/ui_event.h"
#include "xenia/ui/virtual_key.h"
#include "xenia/ui/window_qt.h"

// Autogenerated by `xb premake`.
#include "build/version.h"

DECLARE_bool(debug);

DECLARE_string(hid);

DECLARE_bool(guide_button);
DECLARE_string(config);

DECLARE_bool(clear_memory_page_state);

DECLARE_string(readback_resolve);

DECLARE_bool(readback_memexport);

DEFINE_transient_bool(return_to_ui, false,
                      "Return to UI process when game exits. Set automatically "
                      "when launching from UI.",
                      "General");

DEFINE_uint32(window_size_ui_x, 950, "UI window width in pixels.", "Display");
DEFINE_uint32(window_size_ui_y, 750, "UI window height in pixels.", "Display");

DEFINE_bool(fullscreen, false, "Whether to launch the emulator in fullscreen.",
            "Display");

DEFINE_bool(controller_hotkeys, false, "Hotkeys for Xbox and PS controllers.",
            "General");

DEFINE_string(
    postprocess_antialiasing, "",
    "Post-processing anti-aliasing effect to apply to the image output of the "
    "game.\n"
    "Using post-process anti-aliasing is heavily recommended when AMD "
    "FidelityFX Contrast Adaptive Sharpening or Super Resolution 1.0 is "
    "active.\n"
    "Use: [none, fxaa, fxaa_extreme]\n"
    " none (or any value not listed here):\n"
    "  Don't alter the original image.\n"
    " fxaa:\n"
    "  NVIDIA Fast Approximate Anti-Aliasing 3.11, normal quality preset (12)."
    "\n"
    " fxaa_extreme:\n"
    "  NVIDIA Fast Approximate Anti-Aliasing 3.11, extreme quality preset "
    "(39).",
    "Display");
DEFINE_string(
    postprocess_scaling_and_sharpening, "",
    "Post-processing effect to use for resampling and/or sharpening of the "
    "final display output.\n"
    "Use: [bilinear, cas, fsr]\n"
    " bilinear (or any value not listed here):\n"
    "  Original image at 1:1, simple bilinear stretching for resampling.\n"
    " cas:\n"
    "  Use AMD FidelityFX Contrast Adaptive Sharpening (CAS) for sharpening "
    "at scaling factors of up to 2x2, with additional bilinear stretching for "
    "larger factors.\n"
    " fsr:\n"
    "  Use AMD FidelityFX Super Resolution 1.0 (FSR) for highest-quality "
    "upscaling, or AMD FidelityFX Contrast Adaptive Sharpening for sharpening "
    "while not scaling or downsampling.\n"
    "  For scaling by factors of more than 2x2, multiple FSR passes are done.",
    "Display");
DEFINE_double(
    postprocess_ffx_cas_additional_sharpness,
    xe::ui::Presenter::GuestOutputPaintConfig::kCasAdditionalSharpnessDefault,
    "Additional sharpness for AMD FidelityFX Contrast Adaptive Sharpening "
    "(CAS), from 0 to 1.\n"
    "Higher is sharper.",
    "Display");
DEFINE_uint32(
    postprocess_ffx_fsr_max_upsampling_passes,
    xe::ui::Presenter::GuestOutputPaintConfig::kFsrMaxUpscalingPassesMax,
    "Maximum number of upsampling passes performed in AMD FidelityFX Super "
    "Resolution 1.0 (FSR) before falling back to bilinear stretching after the "
    "final pass.\n"
    "Each pass upscales only to up to 2x2 the previous size. If the game "
    "outputs a 1280x720 image, 1 pass will upscale it to up to 2560x1440 "
    "(below 4K), after 2 passes it will be upscaled to a maximum of 5120x2880 "
    "(including 3840x2160 for 4K), and so on.\n"
    "This variable has no effect if the display resolution isn't very high, "
    "but may be reduced on resolutions like 4K or 8K in case the performance "
    "impact of multiple FSR upsampling passes is too high, or if softer edges "
    "are desired.\n"
    "The default value is the maximum internally supported by Xenia.",
    "Display");
DEFINE_double(
    postprocess_ffx_fsr_sharpness_reduction,
    xe::ui::Presenter::GuestOutputPaintConfig::kFsrSharpnessReductionDefault,
    "Sharpness reduction for AMD FidelityFX Super Resolution 1.0 (FSR), in "
    "stops.\n"
    "Lower is sharper.",
    "Display");
// Dithering to 8bpc is enabled by default since the effect is minor, only
// effects what can't be shown normally by host displays, and nothing is changed
// by it for 8bpc source without resampling.
DEFINE_bool(
    postprocess_dither, true,
    "Dither the final image output from the internal precision to 8 bits per "
    "channel so gradients are smoother.\n"
    "On a 10bpc display, the lower 2 bits will still be kept, but noise will "
    "be added to them - disabling may be recommended for 10bpc, but it "
    "depends on the 10bpc displaying capabilities of the actual display used.",
    "Display");

#if XE_PLATFORM_LINUX
DEFINE_bool(
    use_mangohud, false,
    "Enable MangoHUD overlay when launching games in separate processes.\n"
    "MangoHUD must be installed on your system for this to work.",
    "Linux");
DEFINE_bool(use_gamemode, false,
            "Use Feral GameMode when launching games in separate processes.\n"
            "GameMode must be installed on your system for this to work.",
            "Linux");
#endif
DEFINE_bool(disable_game_window_mouse, false,
            "Disables mouse interactions in the game window, including "
            "double-click to fullscreen and right-click context menu.",
            "General");

namespace xe {
namespace app {

using xe::ui::FileDropEvent;
using xe::ui::KeyEvent;
using xe::ui::MenuItem;
using xe::ui::SafeQString;
using xe::ui::UIEvent;

using namespace xe::hid;
using namespace xe::gpu;

constexpr std::string_view kBaseTitle = "Xenia-edge";

EmulatorWindow::EmulatorWindow(Emulator* emulator,
                               ui::WindowedAppContext& app_context,
                               uint32_t width, uint32_t height,
                               bool is_game_process)
    : emulator_(emulator),
      app_context_(app_context),
      is_game_process_(is_game_process),
      window_listener_(*this),
      window_(ui::Window::Create(app_context, kBaseTitle, width, height,
                                 is_game_process)),
      imgui_drawer_(
          std::make_unique<ui::ImGuiDrawer>(window_.get(), kZOrderImGui)) {
  // Set up resize save timer for both UI and game processes
  resize_save_timer_ = std::make_unique<QTimer>();
  resize_save_timer_->setSingleShot(true);
  QObject::connect(resize_save_timer_.get(), &QTimer::timeout,
                   [this]() { SaveWindowSizeConfig(); });

  // Initialize pending dimensions with current window size
  pending_resize_width_ = width;
  pending_resize_height_ = height;
  base_title_ = std::string(kBaseTitle) +
#ifdef DEBUG
#if _NO_DEBUG_HEAP == 1
                " DEBUG"
#else
                " CHECKED"
#endif
#endif
                " ("
#ifdef XE_BUILD_IS_PR
                "PR#" XE_BUILD_PR_NUMBER " - "
#endif
                XE_BUILD_BRANCH "@" XE_BUILD_COMMIT_SHORT " on " XE_BUILD_DATE
                ")";
}

std::unique_ptr<EmulatorWindow> EmulatorWindow::Create(
    Emulator* emulator, ui::WindowedAppContext& app_context, uint32_t width,
    uint32_t height, bool is_game_process) {
  assert_true(app_context.IsInUIThread());
  std::unique_ptr<EmulatorWindow> emulator_window(new EmulatorWindow(
      emulator, app_context, width, height, is_game_process));
  if (!emulator_window->Initialize()) {
    return nullptr;
  }
  return emulator_window;
}

EmulatorWindow::~EmulatorWindow() {
  // Notify the ImGui drawer that the immediate drawer is being destroyed.
  ShutdownGraphicsSystemPresenterPainting();
}

ui::Presenter* EmulatorWindow::GetGraphicsSystemPresenter() const {
  gpu::GraphicsSystem* graphics_system = emulator_->graphics_system();
  return graphics_system ? graphics_system->presenter() : nullptr;
}

void EmulatorWindow::SetupGraphicsSystemPresenterPainting() {
  ShutdownGraphicsSystemPresenterPainting();

  if (!window_) {
    return;
  }

  ui::Presenter* presenter = GetGraphicsSystemPresenter();
  if (!presenter) {
    return;
  }

  ApplyDisplayConfigForCvars();

  window_->SetPresenter(presenter);

  immediate_drawer_ =
      emulator_->graphics_system()->provider()->CreateImmediateDrawer();
  if (immediate_drawer_) {
    immediate_drawer_->SetPresenter(presenter);
    imgui_drawer_->SetPresenterAndImmediateDrawer(presenter,
                                                  immediate_drawer_.get());
    Profiler::SetUserIO(kZOrderProfiler, window_.get(), presenter,
                        immediate_drawer_.get());
  }
}

void EmulatorWindow::ShutdownGraphicsSystemPresenterPainting() {
  Profiler::SetUserIO(kZOrderProfiler, window_.get(), nullptr, nullptr);
  imgui_drawer_->SetPresenterAndImmediateDrawer(nullptr, nullptr);
  immediate_drawer_.reset();
  if (window_) {
    window_->SetPresenter(nullptr);
  }
}

void EmulatorWindow::OnEmulatorInitialized() {
  // For UI process: emulator is not initialized, just show Qt UI
  if (!is_game_process_) {
    auto* qt_window = dynamic_cast<ui::QtWindow*>(window_.get());
    if (qt_window) {
      // Get the central widget and its layout
      QWidget* central_widget = qt_window->qwindow()->centralWidget();
      if (central_widget && central_widget->layout()) {
        game_list_dialog_qt_ = new GameListDialogQt(central_widget, this);
        // Connect signals from game list dialog
        QObject::connect(game_list_dialog_qt_,
                         &GameListDialogQt::fileOpenRequested,
                         [this]() { FileOpen(); });
        QObject::connect(game_list_dialog_qt_,
                         &GameListDialogQt::launchGameRequested,
                         [this](const std::filesystem::path& path) {
                           LaunchTitleInNewProcess(path);
                         });
        QObject::connect(game_list_dialog_qt_,
                         &GameListDialogQt::settingsRequested,
                         [this]() { ToggleConfigDialog(); });
        // Add it to the layout so it fills the window
        central_widget->layout()->addWidget(game_list_dialog_qt_);
      }
    }

    emulator_initialized_ = true;
    window_->SetMainMenuEnabled(true);
    return;
  }

  // Game process: emulator is fully initialized
  if (!emulator_->kernel_state()
           ->xam_state()
           ->profile_manager()
           ->GetAccountCount()) {
    new NoProfileDialog(imgui_drawer_.get(), this);
    disable_hotkeys_ = true;
  }

  // Game process: enable cursor auto-hide
  window_->SetCursorVisibility(ui::Window::CursorVisibility::kAutoHidden);

  emulator_initialized_ = true;
  window_->SetMainMenuEnabled(true);
  // When the user can see that the emulator isn't initializing anymore (the
  // menu isn't disabled), enter fullscreen if requested.
  if (cvars::fullscreen) {
    SetFullscreen(true);
  }

  if (IsUseNexusForGameBarEnabled()) {
    XELOGE(
        "Xbox Gamebar Enabled, using BACK button instead of GUIDE for "
        "controller hotkeys!!!");
  }

  // Create a thread to listen for controller hotkeys.
  // This thread is started when hid=sdl to prevent SDL analog input issues
  // with Qt's event loop (e.g. in PGR4).
  if (cvars::controller_hotkeys || cvars::hid == "sdl") {
    Gamepad_HotKeys_Listener =
        threading::Thread::Create({}, [&] { GamepadHotKeys(); });
    Gamepad_HotKeys_Listener->set_name("Gamepad HotKeys Listener");
  }

  // Register callback for title-to-title launches from the kernel
  emulator_->set_on_launch_new_title([this](const std::string& host_path,
                                            const std::string& launch_module,
                                            uint32_t launch_flags,
                                            const std::string& launch_data) {
    XELOGI(
        "Launching new title: host_path={}, launch_module={}, flags={}, "
        "data_len={}",
        host_path, launch_module, launch_flags, launch_data.length());

    std::filesystem::path executable_path = xe::filesystem::GetExecutablePath();

#if XE_PLATFORM_WIN32
    auto exe_path_u16 = xe::path_to_utf16(executable_path);
    std::u16string cmd_line = u"\"" + exe_path_u16 + u"\"";

    if (!cvars::config.empty()) {
      cmd_line += u" --config=\"" + xe::to_utf16(cvars::config) + u"\"";
    }
    // Append to log file instead of overwriting
    cmd_line += u" --log_append=true";
    // Preserve return_to_ui through the title-to-title chain
    if (cvars::return_to_ui) {
      cmd_line += u" --return_to_ui=true";
    }
    // Preserve fullscreen state
    if (window_->IsFullscreen()) {
      cmd_line += u" --fullscreen=true";
    }
    if (!launch_module.empty()) {
      cmd_line += u" --launch_module=\"" + xe::to_utf16(launch_module) + u"\"";
    }
    if (launch_flags != 0) {
      cmd_line +=
          u" --launch_flags=" + xe::to_utf16(fmt::format("{}", launch_flags));
    }
    if (!launch_data.empty()) {
      cmd_line += u" --launch_data=" + xe::to_utf16(launch_data);
    }
    if (!host_path.empty()) {
      cmd_line += u" \"" + xe::to_utf16(host_path) + u"\"";
    }

    STARTUPINFOW si = {};
    si.cb = sizeof(si);
    PROCESS_INFORMATION pi = {};

    if (!CreateProcessW(nullptr,
                        const_cast<wchar_t*>(
                            reinterpret_cast<const wchar_t*>(cmd_line.c_str())),
                        nullptr, nullptr, FALSE, CREATE_NEW_CONSOLE, nullptr,
                        nullptr, &si, &pi)) {
      XELOGE("Failed to launch new process: {}", GetLastError());
      return;
    }
    // Allow the new process to bring itself to the foreground
    AllowSetForegroundWindow(pi.dwProcessId);
    CloseHandle(pi.hProcess);
    CloseHandle(pi.hThread);
#else
    pid_t pid = fork();
    if (pid == 0) {
      // Child process
#if XE_PLATFORM_LINUX
      if (cvars::use_mangohud) {
        setenv("MANGOHUD", "1", 1);
      }
#endif  // XE_PLATFORM_LINUX
      std::vector<std::string> arg_storage;
      std::vector<const char*> argv;

#if XE_PLATFORM_LINUX
      std::string gamemode_cmd;
      if (cvars::use_gamemode) {
        gamemode_cmd = "gamemoderun";
        argv.push_back(gamemode_cmd.c_str());
      }
#endif  // XE_PLATFORM_LINUX
      arg_storage.push_back(executable_path.string());
      argv.push_back(arg_storage.back().c_str());

      if (!cvars::config.empty()) {
        arg_storage.push_back("--config=" + cvars::config);
        argv.push_back(arg_storage.back().c_str());
      }
      // Append to log file instead of overwriting
      arg_storage.push_back("--log_append=true");
      argv.push_back(arg_storage.back().c_str());
      // Preserve return_to_ui through the title-to-title chain
      if (cvars::return_to_ui) {
        arg_storage.push_back("--return_to_ui=true");
        argv.push_back(arg_storage.back().c_str());
      }
      // Preserve fullscreen state
      if (window_->IsFullscreen()) {
        arg_storage.push_back("--fullscreen=true");
        argv.push_back(arg_storage.back().c_str());
      }
      if (!launch_module.empty()) {
        arg_storage.push_back("--launch_module=" + launch_module);
        argv.push_back(arg_storage.back().c_str());
      }
      if (launch_flags != 0) {
        arg_storage.push_back(fmt::format("--launch_flags={}", launch_flags));
        argv.push_back(arg_storage.back().c_str());
      }
      if (!launch_data.empty()) {
        arg_storage.push_back("--launch_data=" + launch_data);
        argv.push_back(arg_storage.back().c_str());
      }
      if (!host_path.empty()) {
        arg_storage.push_back(host_path);
        argv.push_back(arg_storage.back().c_str());
      }
      argv.push_back(nullptr);

#if XE_PLATFORM_LINUX
      if (cvars::use_gamemode) {
        execvp(gamemode_cmd.c_str(), const_cast<char**>(argv.data()));
      } else {
        execv(executable_path.c_str(), const_cast<char**>(argv.data()));
      }
#else
      execv(executable_path.c_str(), const_cast<char**>(argv.data()));
#endif  // XE_PLATFORM_LINUX
      std::exit(1);
    } else if (pid < 0) {
      XELOGE("Failed to fork process");
      return;
    }
#endif
    // Exit directly - don't go through window close path which would
    // spawn a UI process if return_to_ui is set
    xe::FlushLog();
    std::exit(0);
  });

  // Register callback for disc swap to update title bar
  emulator_->set_on_disc_swap([this](uint8_t new_disc_number) {
    swapped_disc_number_ = new_disc_number;
    app_context_.CallInUIThread([this]() { UpdateTitle(); });
  });
}

void EmulatorWindow::EmulatorWindowListener::OnClosing(ui::UIEvent& e) {
  // Game process: spawn UI if return_to_ui is set, then exit
  if (emulator_window_.is_game_process_) {
    if (cvars::return_to_ui) {
      // Spawn UI process (xenia with no target)
      std::filesystem::path executable_path =
          xe::filesystem::GetExecutablePath();

#if XE_PLATFORM_WIN32
      auto exe_path_u16 = xe::path_to_utf16(executable_path);
      std::u16string cmd_line = u"\"" + exe_path_u16 + u"\"";

      if (!cvars::config.empty()) {
        cmd_line += u" --config=\"" + xe::to_utf16(cvars::config) + u"\"";
      }

      STARTUPINFOW si = {};
      si.cb = sizeof(si);
      PROCESS_INFORMATION pi = {};

      if (CreateProcessW(nullptr,
                         const_cast<wchar_t*>(reinterpret_cast<const wchar_t*>(
                             cmd_line.c_str())),
                         nullptr, nullptr, FALSE, CREATE_NEW_CONSOLE, nullptr,
                         nullptr, &si, &pi)) {
        // Allow the new process to bring itself to the foreground
        AllowSetForegroundWindow(pi.dwProcessId);
        CloseHandle(pi.hProcess);
        CloseHandle(pi.hThread);
        XELOGI("Spawned UI process");
      } else {
        XELOGE("Failed to spawn UI process: {}", GetLastError());
      }
#else
      pid_t pid = fork();
      if (pid == 0) {
        // Child process - become UI
        std::vector<const char*> argv;
#if XE_PLATFORM_LINUX
        std::string gamemode_cmd;
        if (cvars::use_gamemode) {
          gamemode_cmd = "gamemoderun";
          argv.push_back(gamemode_cmd.c_str());
        }
#endif  // XE_PLATFORM_LINUX
        argv.push_back(executable_path.c_str());

        std::string config_arg;
        if (!cvars::config.empty()) {
          config_arg = "--config=" + cvars::config;
          argv.push_back(config_arg.c_str());
        }
        argv.push_back(nullptr);

#if XE_PLATFORM_LINUX
        if (cvars::use_gamemode) {
          execvp(gamemode_cmd.c_str(), const_cast<char**>(argv.data()));
        } else {
          execv(executable_path.c_str(), const_cast<char**>(argv.data()));
        }
#else
        execv(executable_path.c_str(), const_cast<char**>(argv.data()));
#endif  // XE_PLATFORM_LINUX
        std::exit(1);
      } else if (pid > 0) {
        XELOGI("Spawned UI process");
      } else {
        XELOGE("Failed to fork UI process");
      }
#endif
    }

    xe::FlushLog();
    std::exit(0);
  }

  // UI process: let Qt handle the exit
  emulator_window_.app_context_.QuitFromUIThread();
}

void EmulatorWindow::EmulatorWindowListener::OnFileDrop(ui::FileDropEvent& e) {
  emulator_window_.FileDrop(e.filename());
}

void EmulatorWindow::EmulatorWindowListener::OnResize(ui::UISetupEvent& e) {
  // Persist window size for both UI and game processes
  auto window = emulator_window_.window();
  if (window && emulator_window_.resize_save_timer_) {
    // Update pending dimensions with current window size
    emulator_window_.pending_resize_width_ = window->GetActualLogicalWidth();
    emulator_window_.pending_resize_height_ = window->GetActualLogicalHeight();

    // Reset the timer - it will fire 300ms after the last resize event
    emulator_window_.resize_save_timer_->stop();
    emulator_window_.resize_save_timer_->start(300);  // 300ms delay
  }
}

void EmulatorWindow::SaveWindowSizeConfig() {
  // Don't save window dimensions when in fullscreen mode
  if (window_ && window_->IsFullscreen()) {
    return;
  }

  if (is_game_process_) {
    // Game process - save to game-specific config
    if (!emulator_ || !emulator_->is_title_open()) {
      return;  // No title loaded yet
    }

    uint32_t title_id = emulator_->title_id();
    if (title_id == 0) {
      return;
    }

    // Load existing config, update both values, save once
    toml::table config_table = config::LoadGameConfig(title_id);

    // Ensure Display category exists
    if (!config_table.contains("Display")) {
      config_table.insert("Display", toml::table{});
    }

    auto* display_table = config_table["Display"].as_table();
    if (display_table) {
      display_table->insert_or_assign(
          "window_size_game_x", static_cast<int64_t>(pending_resize_width_));
      display_table->insert_or_assign(
          "window_size_game_y", static_cast<int64_t>(pending_resize_height_));
    }

    config::SaveGameConfig(title_id, config_table);
  } else {
    // UI process - save to main config
    if (cvars::window_size_ui_x != pending_resize_width_ ||
        cvars::window_size_ui_y != pending_resize_height_) {
      XELOGI("UI window resized: {}x{} -> {}x{}", cvars::window_size_ui_x,
             cvars::window_size_ui_y, pending_resize_width_,
             pending_resize_height_);

      // Update the cvars using OVERRIDE to properly set config values
      OVERRIDE_uint32(window_size_ui_x, pending_resize_width_);
      OVERRIDE_uint32(window_size_ui_y, pending_resize_height_);

      // Save the config to persist the changes
      config::SaveConfig();
    }
  }
}

void EmulatorWindow::EmulatorWindowListener::OnKeyDown(ui::KeyEvent& e) {
  emulator_window_.OnKeyDown(e);
}

void EmulatorWindow::EmulatorWindowListener::OnMouseDown(ui::MouseEvent& e) {
  emulator_window_.OnMouseDown(e);
}

void EmulatorWindow::EmulatorWindowListener::OnMouseUp(ui::MouseEvent& e) {
  emulator_window_.OnMouseUp(e);
}

void EmulatorWindow::EmulatorWindowListener::OnMouseDoubleClick(
    ui::MouseEvent& e) {
  emulator_window_.OnMouseDoubleClick(e);
}

bool EmulatorWindow::Initialize() {
  window_->AddListener(&window_listener_);
  window_->AddInputListener(&window_listener_, kZOrderEmulatorWindowInput);

  // Main menu - only create for UI process, not game process
  if (!is_game_process_) {
    // UI process - create the menu bar
    // FIXME: This code is really messy.
    auto main_menu = MenuItem::Create(MenuItem::Type::kNormal);

    auto file_menu = MenuItem::Create(MenuItem::Type::kPopup, "&File");
    file_menu_ = file_menu.get();
    {
      auto open_item =
          MenuItem::Create(MenuItem::Type::kString, "&Open...", "Ctrl+O",
                           std::bind(&EmulatorWindow::FileOpen, this));
      file_open_item_ = open_item.get();
      file_menu->AddChild(std::move(open_item));
#ifdef DEBUG
      file_menu->AddChild(MenuItem::Create(MenuItem::Type::kSeparator));
      file_menu->AddChild(
          MenuItem::Create(MenuItem::Type::kString, "Close",
                           std::bind(&EmulatorWindow::FileClose, this)));
#endif  // #ifdef DEBUG
      file_menu->AddChild(MenuItem::Create(MenuItem::Type::kSeparator));
      file_menu->AddChild(MenuItem::Create(
          MenuItem::Type::kString, "Show content directory...",
          std::bind(&EmulatorWindow::ShowContentDirectory, this)));
      file_menu->AddChild(MenuItem::Create(MenuItem::Type::kSeparator));
      file_menu->AddChild(
          MenuItem::Create(MenuItem::Type::kString, "E&xit", "Alt+F4",
                           [this]() { window_->RequestClose(); }));
    }
    main_menu->AddChild(std::move(file_menu));

    // Profile Menu
    auto profile_menu = MenuItem::Create(MenuItem::Type::kPopup, "&Profile");
    {
      profile_menu->AddChild(MenuItem::Create(
          MenuItem::Type::kString, "&Show Profile Menu", "",
          std::bind(&EmulatorWindow::ToggleProfilesConfigDialog, this)));
    }
    main_menu->AddChild(std::move(profile_menu));

    // Configuration menu.
    auto config_menu =
        MenuItem::Create(MenuItem::Type::kPopup, "&Configuration");
    {
      config_menu->AddChild(
          MenuItem::Create(MenuItem::Type::kString, "&APU",
                           [this]() { OpenConfigDialog("APU"); }));
      config_menu->AddChild(
          MenuItem::Create(MenuItem::Type::kString, "&Content",
                           [this]() { OpenConfigDialog("Content"); }));
      config_menu->AddChild(
          MenuItem::Create(MenuItem::Type::kString, "C&PU",
                           [this]() { OpenConfigDialog("CPU"); }));
#if XE_PLATFORM_WIN32
      config_menu->AddChild(
          MenuItem::Create(MenuItem::Type::kString, "D3D1&2",
                           [this]() { OpenConfigDialog("D3D12"); }));
#endif
      config_menu->AddChild(
          MenuItem::Create(MenuItem::Type::kString, "&Display",
                           [this]() { OpenConfigDialog("Display"); }));
      config_menu->AddChild(
          MenuItem::Create(MenuItem::Type::kString, "&General",
                           [this]() { OpenConfigDialog("General"); }));
      config_menu->AddChild(
          MenuItem::Create(MenuItem::Type::kString, "G&PU",
                           [this]() { OpenConfigDialog("GPU"); }));
      config_menu->AddChild(
          MenuItem::Create(MenuItem::Type::kString, "&HID",
                           [this]() { OpenConfigDialog("HID"); }));
#if XE_PLATFORM_WIN32
      config_menu->AddChild(
          MenuItem::Create(MenuItem::Type::kString, "HID.Win&Key",
                           [this]() { OpenConfigDialog("HID.WinKey"); }));
#endif
      config_menu->AddChild(
          MenuItem::Create(MenuItem::Type::kString, "&Kernel",
                           [this]() { OpenConfigDialog("Kernel"); }));
#if XE_PLATFORM_LINUX
      config_menu->AddChild(
          MenuItem::Create(MenuItem::Type::kString, "&Linux",
                           [this]() { OpenConfigDialog("Linux"); }));
#endif
      config_menu->AddChild(
          MenuItem::Create(MenuItem::Type::kString, "&Logging",
                           [this]() { OpenConfigDialog("Logging"); }));
      config_menu->AddChild(
          MenuItem::Create(MenuItem::Type::kString, "&Memory",
                           [this]() { OpenConfigDialog("Memory"); }));
      config_menu->AddChild(
          MenuItem::Create(MenuItem::Type::kString, "&Profiles",
                           [this]() { OpenConfigDialog("Profiles"); }));
      config_menu->AddChild(
          MenuItem::Create(MenuItem::Type::kString, "&SDL",
                           [this]() { OpenConfigDialog("SDL"); }));
      config_menu->AddChild(
          MenuItem::Create(MenuItem::Type::kString, "S&torage",
                           [this]() { OpenConfigDialog("Storage"); }));
      config_menu->AddChild(
          MenuItem::Create(MenuItem::Type::kString, "&UI",
                           [this]() { OpenConfigDialog("UI"); }));
      config_menu->AddChild(
          MenuItem::Create(MenuItem::Type::kString, "&Video",
                           [this]() { OpenConfigDialog("Video"); }));
      config_menu->AddChild(
          MenuItem::Create(MenuItem::Type::kString, "V&ulkan",
                           [this]() { OpenConfigDialog("Vulkan"); }));
#if XE_PLATFORM_WIN32
      config_menu->AddChild(
          MenuItem::Create(MenuItem::Type::kString, "&Win32",
                           [this]() { OpenConfigDialog("Win32"); }));
#endif
      config_menu->AddChild(
          MenuItem::Create(MenuItem::Type::kString, "&x64",
                           [this]() { OpenConfigDialog("x64"); }));
      config_menu->AddChild(
          MenuItem::Create(MenuItem::Type::kString, "X&Config",
                           [this]() { OpenConfigDialog("XConfig"); }));
    }
    main_menu->AddChild(std::move(config_menu));

    // Tools menu.
    auto tools_menu = MenuItem::Create(MenuItem::Type::kPopup, "&Tools");
    {
      tools_menu->AddChild(
          MenuItem::Create(MenuItem::Type::kString, "&Install Content...",
                           std::bind(&EmulatorWindow::InstallContent, this)));
      tools_menu->AddChild(MenuItem::Create(MenuItem::Type::kSeparator));
      auto zar_menu = MenuItem::Create(MenuItem::Type::kPopup, "&Zar Package");
      zar_menu->AddChild(
          MenuItem::Create(MenuItem::Type::kString, "Create",
                           std::bind(&EmulatorWindow::CreateZarchive, this)));
      zar_menu->AddChild(
          MenuItem::Create(MenuItem::Type::kString, "Extract",
                           std::bind(&EmulatorWindow::ExtractZarchive, this)));
      tools_menu->AddChild(std::move(zar_menu));
    }
    main_menu->AddChild(std::move(tools_menu));

    // Help menu.
    auto help_menu = MenuItem::Create(MenuItem::Type::kPopup, "&Help");
    {
      help_menu->AddChild(
          MenuItem::Create(MenuItem::Type::kString, "FA&Q...",
                           std::bind(&EmulatorWindow::ShowFAQ, this)));
      help_menu->AddChild(MenuItem::Create(MenuItem::Type::kSeparator));
      help_menu->AddChild(MenuItem::Create(
          MenuItem::Type::kString, "Game &compatibility...",
          std::bind(&EmulatorWindow::ShowCompatibility, this)));
      help_menu->AddChild(MenuItem::Create(MenuItem::Type::kSeparator));
      help_menu->AddChild(
          MenuItem::Create(MenuItem::Type::kString, "&About...",
                           std::bind(&EmulatorWindow::ShowAbout, this)));
    }
    main_menu->AddChild(std::move(help_menu));

    window_->SetMainMenu(std::move(main_menu));

    window_->SetMainMenuEnabled(false);
  }  // End of menu creation for UI process

  UpdateTitle();

  if (!window_->Open()) {
    XELOGE("Failed to open the platform window");
    return false;
  }

  Profiler::SetUserIO(kZOrderProfiler, window_.get(), nullptr, nullptr);

  return true;
}

const char* EmulatorWindow::GetCvarValueForSwapPostEffect(
    gpu::CommandProcessor::SwapPostEffect effect) {
  switch (effect) {
    case gpu::CommandProcessor::SwapPostEffect::kFxaa:
      return "fxaa";
    case gpu::CommandProcessor::SwapPostEffect::kFxaaExtreme:
      return "fxaa_extreme";
    default:
      return "";
  }
}

gpu::CommandProcessor::SwapPostEffect
EmulatorWindow::GetSwapPostEffectForCvarValue(const std::string& cvar_value) {
  if (cvar_value == GetCvarValueForSwapPostEffect(
                        gpu::CommandProcessor::SwapPostEffect::kFxaa)) {
    return gpu::CommandProcessor::SwapPostEffect::kFxaa;
  }
  if (cvar_value == GetCvarValueForSwapPostEffect(
                        gpu::CommandProcessor::SwapPostEffect::kFxaaExtreme)) {
    return gpu::CommandProcessor::SwapPostEffect::kFxaaExtreme;
  }
  return gpu::CommandProcessor::SwapPostEffect::kNone;
}

const char* EmulatorWindow::GetCvarValueForGuestOutputPaintEffect(
    ui::Presenter::GuestOutputPaintConfig::Effect effect) {
  switch (effect) {
    case ui::Presenter::GuestOutputPaintConfig::Effect::kCas:
      return "cas";
    case ui::Presenter::GuestOutputPaintConfig::Effect::kFsr:
      return "fsr";
    default:
      return "";
  }
}

ui::Presenter::GuestOutputPaintConfig::Effect
EmulatorWindow::GetGuestOutputPaintEffectForCvarValue(
    const std::string& cvar_value) {
  if (cvar_value == GetCvarValueForGuestOutputPaintEffect(
                        ui::Presenter::GuestOutputPaintConfig::Effect::kCas)) {
    return ui::Presenter::GuestOutputPaintConfig::Effect::kCas;
  }
  if (cvar_value == GetCvarValueForGuestOutputPaintEffect(
                        ui::Presenter::GuestOutputPaintConfig::Effect::kFsr)) {
    return ui::Presenter::GuestOutputPaintConfig::Effect::kFsr;
  }
  return ui::Presenter::GuestOutputPaintConfig::Effect::kBilinear;
}

ui::Presenter::GuestOutputPaintConfig
EmulatorWindow::GetGuestOutputPaintConfigForCvars() {
  ui::Presenter::GuestOutputPaintConfig paint_config;
  paint_config.SetAllowOverscanCutoff(true);
  paint_config.SetEffect(GetGuestOutputPaintEffectForCvarValue(
      cvars::postprocess_scaling_and_sharpening));
  paint_config.SetCasAdditionalSharpness(
      float(cvars::postprocess_ffx_cas_additional_sharpness));
  paint_config.SetFsrMaxUpsamplingPasses(
      cvars::postprocess_ffx_fsr_max_upsampling_passes);
  paint_config.SetFsrSharpnessReduction(
      float(cvars::postprocess_ffx_fsr_sharpness_reduction));
  paint_config.SetDither(cvars::postprocess_dither);
  return paint_config;
}

void EmulatorWindow::ApplyDisplayConfigForCvars() {
  gpu::GraphicsSystem* graphics_system = emulator_->graphics_system();
  if (!graphics_system) {
    return;
  }

  gpu::CommandProcessor* command_processor =
      graphics_system->command_processor();
  if (command_processor) {
    command_processor->SetDesiredSwapPostEffect(
        GetSwapPostEffectForCvarValue(cvars::postprocess_antialiasing));
  }

  ui::Presenter* presenter = graphics_system->presenter();
  if (presenter) {
    presenter->SetGuestOutputPaintConfigFromUIThread(
        GetGuestOutputPaintConfigForCvars());
  }
}

void EmulatorWindow::UpdateAntiAliasingCvar(
    gpu::CommandProcessor::SwapPostEffect effect) {
  if (GetSwapPostEffectForCvarValue(cvars::postprocess_antialiasing) !=
      effect) {
    OVERRIDE_string(postprocess_antialiasing,
                    GetCvarValueForSwapPostEffect(effect));
  }
}

void EmulatorWindow::UpdateScalingAndSharpeningCvar(
    ui::Presenter::GuestOutputPaintConfig::Effect effect) {
  auto cvars_config = GetGuestOutputPaintConfigForCvars();
  if (cvars_config.GetEffect() != effect) {
    OVERRIDE_string(postprocess_scaling_and_sharpening,
                    GetCvarValueForGuestOutputPaintEffect(effect));
  }
}

void EmulatorWindow::UpdateFsrSharpnessCvar(float value) {
  auto cvars_config = GetGuestOutputPaintConfigForCvars();
  if (cvars_config.GetFsrSharpnessReduction() != value) {
    OVERRIDE_double(postprocess_ffx_fsr_sharpness_reduction, value);
  }
}

void EmulatorWindow::UpdateCasSharpnessCvar(float value) {
  auto cvars_config = GetGuestOutputPaintConfigForCvars();
  if (cvars_config.GetCasAdditionalSharpness() != value) {
    OVERRIDE_double(postprocess_ffx_cas_additional_sharpness, value);
  }
}

void EmulatorWindow::UpdateDitherCvar(bool value) {
  auto cvars_config = GetGuestOutputPaintConfigForCvars();
  if (cvars_config.GetDither() != value) {
    OVERRIDE_bool(postprocess_dither, value);
  }
}

void EmulatorWindow::UpdateFsrMaxUpsamplingPassesCvar(uint32_t value) {
  auto cvars_config = GetGuestOutputPaintConfigForCvars();
  if (cvars_config.GetFsrMaxUpsamplingPasses() != value) {
    OVERRIDE_uint32(postprocess_ffx_fsr_max_upsampling_passes, value);
  }
}

void EmulatorWindow::OnKeyDown(ui::KeyEvent& e) {
  if (!emulator_initialized_) {
    return;
  }

  switch (e.virtual_key()) {
    case ui::VirtualKey::kO: {
      if (!e.is_ctrl_pressed()) {
        return;
      }
      FileOpen();
    } break;
    case ui::VirtualKey::kMultiply: {
      CpuTimeScalarReset();
    } break;
    case ui::VirtualKey::kSubtract: {
      CpuTimeScalarSetHalf();
    } break;
    case ui::VirtualKey::kAdd: {
      CpuTimeScalarSetDouble();
    } break;

    case ui::VirtualKey::kF3: {
      Profiler::ToggleDisplay();
    } break;

    case ui::VirtualKey::kF4: {
      GpuTraceFrame();
    } break;
    case ui::VirtualKey::kF5: {
      GpuClearCaches();
    } break;

    case ui::VirtualKey::kF6: {
      ToggleDisplayConfigDialog();
    } break;
    case ui::VirtualKey::kF7: {
      TogglePerformanceTuningDialog();
    } break;
    case ui::VirtualKey::kF11: {
      ToggleFullscreen();
    } break;
    case ui::VirtualKey::kF12: {
      TakeScreenshot();
    } break;

    case ui::VirtualKey::kEscape: {
      // Allow users to escape fullscreen (but not enter it).
      if (!window_->IsFullscreen()) {
        return;
      }
      SetFullscreen(false);
    } break;

    case ui::VirtualKey::kPause: {
      CpuBreakIntoDebugger();
    } break;
    case ui::VirtualKey::kCancel: {
      CpuBreakIntoHostDebugger();
    } break;

    default:
      return;
  }

  e.set_handled(true);
}

void EmulatorWindow::OnMouseDown(const ui::MouseEvent& e) {
  if (e.button() == ui::MouseEvent::Button::kRight) {
    if (cvars::disable_game_window_mouse) {
      return;
    }
    // Don't show context menu if a dialog (other than context menu) is open
    if (!context_menu_ && imgui_drawer() && imgui_drawer()->HasOpenDialogs()) {
      return;
    }
    ToggleContextMenu();
  }
}

void EmulatorWindow::ToggleContextMenu(bool use_cursor_position) {
  // If menu is already open, close it instead of opening a new one
  if (context_menu_) {
    context_menu_->CloseMenu();
    context_menu_ = nullptr;
    return;
  }

  // Get input system for gamepad navigation support
  auto input_sys = emulator()->input_system();

  // Create new ImGui context menu
  auto* context_menu = new ui::ImGuiContextMenu(imgui_drawer(), input_sys);
  context_menu_ = context_menu;

  // Set callback to clear our pointer when menu closes
  context_menu->SetOnCloseCallback([this]() { context_menu_ = nullptr; });

  context_menu->AddAction(
      window_->IsFullscreen() ? "Exit Fullscreen" : "Fullscreen",
      [this]() { ToggleFullscreen(); }, "F11");

  // Get current vibration state
  bool vibration_enabled = false;
  if (input_sys) {
    vibration_enabled = input_sys->GetVibrationCvar();
  }

  std::string vibration_text =
      std::string("Vibration: ") + (vibration_enabled ? "On" : "Off");
  context_menu->AddAction(vibration_text,
                          [this]() { ToggleControllerVibration(); });

  context_menu->AddAction(
      "Take Screenshot", [this]() { TakeScreenshot(); }, "F12");

  context_menu->AddSeparator();

  context_menu->AddAction(
      "Post-Processing", [this]() { ToggleDisplayConfigDialog(); }, "F6");

  context_menu->AddAction(
      "Performance Settings", [this]() { TogglePerformanceTuningDialog(); },
      "F7");

  context_menu->AddSeparator();

  context_menu->AddAction("Profiles Menu",
                          [this]() { ToggleProfilesConfigDialog(); });

  context_menu->AddAction("XMP Audio Player",
                          [this]() { ToggleXMPConfigDialog(); });

  context_menu->AddSeparator();

  context_menu->AddAction("Quit Game", [this, input_sys]() {
    new ui::ImGuiConfirmDialog(
        imgui_drawer(), "Quit Game",
        "Are you sure you want to quit?\n\nAny unsaved progress will be lost.",
        [this](bool confirmed) {
          if (confirmed) {
            window_->RequestClose();
          }
        },
        input_sys);
  });

  // Show menu centered (ImGui handles positioning)
  context_menu->Show();
}

void EmulatorWindow::OnMouseUp(const ui::MouseEvent& e) {
  last_mouse_up = steady_clock::now();
}

void EmulatorWindow::TakeScreenshot() {
  xe::ui::RawImage image;

  imgui_drawer_->EnableNotifications(false);

  if (!GetGraphicsSystemPresenter()->CaptureGuestOutput(image) ||
      GetGraphicsSystemPresenter() == nullptr) {
    XELOGE("Failed to capture guest output for screenshot");
    return;
  }

  imgui_drawer_->EnableNotifications(true);
  ExportScreenshot(image);
}

void EmulatorWindow::ExportScreenshot(const xe::ui::RawImage& image) {
  auto t = std::time(nullptr);

  // The format is: Year-Month-DayTHours-Minutes-Seconds based off ISO 8601
  std::string datetime =
      fmt::format("{:%Y-%m-%dT%H-%M-%S}", *std::localtime(&t));

  // Get the title id of the game because some titles contain characters that
  // cannot be used as a directory
  std::string title_id;
  if (emulator()->title_id()) {
    title_id = fmt::format("{:08X}", emulator()->title_id());
  } else {
    XELOGE("Failed to get the current title id");
    return;
  }

  // Find where xenia.exe or xenia_edge.exe is located and create a
  // screenshots folder
  auto screenshot_path =
      (xe::filesystem::GetExecutableFolder() / "screenshots" / title_id);

  if (!std::filesystem::exists(screenshot_path)) {
    std::filesystem::create_directories(screenshot_path);
  }

  std::string filename = fmt::format("{} - {}.png", title_id, datetime);
  SaveImage(screenshot_path / filename, image);

  const std::string notification_text =
      fmt::format("Screenshot saved: {}", filename);

  app_context_.CallInUIThread([this, notification_text]() {
    if (imgui_drawer()) {
      new ui::HostNotificationWindow(imgui_drawer(), "Screenshot Created!",
                                     notification_text, 0);
    }
  });
}

// Converts a RawImage into a PNG file
void EmulatorWindow::SaveImage(const std::filesystem::path& filepath,
                               const xe::ui::RawImage& image) {
  auto file = std::ofstream(filepath, std::ios::binary);
  if (!file.is_open()) {
    XELOGE("Failed to open file for writing: {}", filepath);
    return;
  }

  auto result = stbi_write_png_to_func(
      [](void* context, void* data, int size) {
        auto file = reinterpret_cast<std::ofstream*>(context);
        file->write(reinterpret_cast<const char*>(data), size);
      },
      &file, image.width, image.height, 4, image.data.data(),
      (int)image.stride);
  if (result == 0) {
    XELOGE("Failed to write PNG to file: {}", filepath);
    return;
  }
}

void EmulatorWindow::OnMouseDoubleClick(const ui::MouseEvent& e) {
  if (cvars::disable_game_window_mouse) {
    return;
  }
  // Don't toggle fullscreen if any ImGui dialogs are open
  // This allows users to double-click to select text in dialog input fields
  if (imgui_drawer_ && imgui_drawer_->HasOpenDialogs()) {
    return;
  }

  // Only toggle fullscreen on left button double-click
  if (e.button() == ui::MouseEvent::Button::kLeft) {
    ToggleFullscreen();
  }
}

void EmulatorWindow::FileDrop(const std::filesystem::path& path) {
  if (!emulator_initialized_) {
    return;
  }

  // Launch the title in a new process instead of loading it here
  LaunchTitleInNewProcess(path);
}

void EmulatorWindow::FileOpen() {
  std::filesystem::path path;

  auto file_picker = xe::ui::FilePicker::Create();
  file_picker->set_mode(ui::FilePicker::Mode::kOpen);
  file_picker->set_type(ui::FilePicker::Type::kFile);
  file_picker->set_multi_selection(false);
  file_picker->set_title("Select Content Package");

  auto initial_dir = GetFilePickerInitialDirectory();
  if (!initial_dir.empty()) {
    file_picker->set_initial_directory(initial_dir);
  }

  file_picker->set_extensions({
      {"Supported Files", "*.iso;*.xex;*.zar;*.*"},
      {"Disc Image (*.iso)", "*.iso"},
      {"Disc Archive (*.zar)", "*.zar"},
      {"Xbox Executable (*.xex)", "*.xex"},
      //{"Content Package (*.xcp)", "*.xcp" },
      {"All Files (*.*)", "*.*"},
  });
  if (file_picker->Show(window_.get())) {
    auto selected_files = file_picker->selected_files();
    if (!selected_files.empty()) {
      path = selected_files[0];
    }
    // Launch the title in a new process instead of loading it here
    if (!path.empty()) {
      LaunchTitleInNewProcess(path);
    }
  }
}

void EmulatorWindow::FileClose() { emulator_->TerminateTitle(); }

void EmulatorWindow::InstallContent() {
  std::vector<std::filesystem::path> paths;

  auto file_picker = xe::ui::FilePicker::Create();
  file_picker->set_mode(ui::FilePicker::Mode::kOpen);
  file_picker->set_type(ui::FilePicker::Type::kFile);
  file_picker->set_multi_selection(true);
  file_picker->set_title("Select Content Package(s)");

  auto initial_dir = GetFilePickerInitialDirectory();
  if (!initial_dir.empty()) {
    file_picker->set_initial_directory(initial_dir);
  }

  file_picker->set_extensions({
      {"All Files (*.*)", "*.*"},
  });
  if (file_picker->Show(window_.get())) {
    paths = file_picker->selected_files();
  }

  if (paths.empty()) {
    return;
  }

  std::shared_ptr<std::vector<Emulator::ContentInstallEntry>>
      content_installation_status =
          std::make_shared<std::vector<Emulator::ContentInstallEntry>>();

  for (const auto& path : paths) {
    content_installation_status->push_back({path});
  }

  for (auto& entry : *content_installation_status) {
    emulator_->ProcessContentPackageHeader(entry.path_, entry);
  }

  // Show dialog first, then start installation so the dialog is visible
  // before any fast-completing installations finish
  auto* dialog = new ui::ContentInstallDialogQt(
      nullptr, emulator_->content_root(), content_installation_status);
  dialog->show();
  dialog->raise();
  dialog->activateWindow();

  auto installationThread = std::thread([this, content_installation_status] {
    for (auto& entry : *content_installation_status) {
      emulator_->InstallContentPackage(entry.path_, entry);
    }
  });
  installationThread.detach();
}

void EmulatorWindow::ExtractZarchive() {
  std::vector<std::filesystem::path> zarchive_files;
  std::filesystem::path extract_dir;

  auto file_picker = xe::ui::FilePicker::Create();
  file_picker->set_mode(ui::FilePicker::Mode::kOpen);
  file_picker->set_type(ui::FilePicker::Type::kFile);
  file_picker->set_multi_selection(true);
  file_picker->set_title("Select Zar Package");

  auto initial_dir = GetFilePickerInitialDirectory();
  if (!initial_dir.empty()) {
    file_picker->set_initial_directory(initial_dir);
  }

  file_picker->set_extensions({
      {"Zarchive Files (*.zar)", "*.zar"},
  });

  if (file_picker->Show(window_.get())) {
    zarchive_files = file_picker->selected_files();
  }

  if (zarchive_files.empty()) {
    return;
  }

  file_picker->set_type(ui::FilePicker::Type::kDirectory);
  file_picker->set_title("Select Directory to Extract");

  if (file_picker->Show(window_.get())) {
    extract_dir = file_picker->selected_files().front();
  }

  if (extract_dir.empty()) {
    return;
  }

  auto zarchive_entries =
      std::make_shared<std::vector<Emulator::ZarchiveEntry>>();

  for (auto& zarchive_file_path : zarchive_files) {
    auto abs_path = std::filesystem::absolute(zarchive_file_path);
    std::filesystem::path abs_extract_dir;

    if (zarchive_files.size() > 1) {
      abs_extract_dir =
          std::filesystem::absolute((extract_dir / abs_path.stem()));
    } else {
      abs_extract_dir = std::filesystem::absolute(extract_dir);
    }

    zarchive_entries->emplace_back(abs_path, abs_extract_dir,
                                   Emulator::ZarchiveOperation::Extract);
    auto& entry = zarchive_entries->back();
    entry.name_ = xe::path_to_utf8(abs_path.filename());

    // Extract icon/title from STFS content within the archive
    auto device = std::make_unique<vfs::DiscZarchiveDevice>("", abs_path);
    if (device->Initialize()) {
      std::function<void(vfs::Entry*)> find_stfs_info = [&](vfs::Entry* e) {
        if (!entry.icon_data_.empty()) return;
        if (e->attributes() & vfs::kFileAttributeDirectory) {
          for (auto& child : e->children()) {
            find_stfs_info(child.get());
          }
        } else if (e->size() >= sizeof(vfs::XContentContainerHeader)) {
          vfs::File* file = nullptr;
          if (e->Open(vfs::FileAccess::kGenericRead, &file) ==
                  X_STATUS_SUCCESS &&
              file) {
            std::vector<uint8_t> header_data(
                sizeof(vfs::XContentContainerHeader));
            size_t bytes_read = 0;
            if (file->ReadSync(header_data, 0, &bytes_read) ==
                    X_STATUS_SUCCESS &&
                bytes_read == sizeof(vfs::XContentContainerHeader)) {
              auto* header = reinterpret_cast<vfs::XContentContainerHeader*>(
                  header_data.data());
              if (header->content_header.is_magic_valid()) {
                auto title_name = xe::to_utf8(
                    header->content_metadata.display_name(XLanguage::kEnglish));
                if (!title_name.empty()) {
                  entry.name_ = title_name;
                }

                if (header->content_metadata.title_thumbnail_size > 0 &&
                    header->content_metadata.title_thumbnail_size <=
                        vfs::XContentMetadata::kThumbLengthV1) {
                  entry.icon_data_.assign(
                      header->content_metadata.title_thumbnail,
                      header->content_metadata.title_thumbnail +
                          header->content_metadata.title_thumbnail_size);
                }
              }
            }
            file->Destroy();
          }
        }
      };
      auto* root = device->ResolvePath("/");
      if (root) {
        find_stfs_info(root);
      }
    }
  }

  auto* dialog = new ui::ContentInstallDialogQt(nullptr, zarchive_entries);
  dialog->show();
  dialog->raise();
  dialog->activateWindow();

  auto extractThread = std::thread([this, zarchive_entries] {
    for (auto& entry : *zarchive_entries) {
      emulator_->ExtractZarchivePackage(entry);
    }
  });
  extractThread.detach();
}

void EmulatorWindow::CreateZarchive() {
  std::vector<std::filesystem::path> content_dirs;
  std::filesystem::path zarchive_dir;

  auto file_picker = xe::ui::FilePicker::Create();
  file_picker->set_mode(ui::FilePicker::Mode::kOpen);
  file_picker->set_type(ui::FilePicker::Type::kDirectory);
  file_picker->set_multi_selection(true);
  file_picker->set_title("Select Contents");

  auto initial_dir = GetFilePickerInitialDirectory();
  if (!initial_dir.empty()) {
    file_picker->set_initial_directory(initial_dir);
  }

  if (file_picker->Show(window_.get())) {
    content_dirs = file_picker->selected_files();
  }

  if (content_dirs.empty()) {
    return;
  }

  // Scan for STFS content to get game name/icon before showing save dialog.
  struct SourceInfo {
    std::filesystem::path stfs_path;
    std::string title_name;
    std::vector<uint8_t> icon_data;
  };
  std::vector<SourceInfo> source_infos(content_dirs.size());

  for (size_t i = 0; i < content_dirs.size(); i++) {
    auto abs_dir = std::filesystem::absolute(content_dirs[i]);
    std::error_code ec;
    // Top-level only to avoid false-positives on embedded STFS (DLC, etc.)
    for (auto const& dirEntry :
         std::filesystem::directory_iterator(abs_dir, ec)) {
      if (!source_infos[i].icon_data.empty()) break;
      if (dirEntry.is_regular_file()) {
        const auto header =
            vfs::XContentContainerDevice::ReadContainerHeader(dirEntry.path());
        if (header && header->content_header.is_magic_valid()) {
          source_infos[i].stfs_path = dirEntry.path();

          source_infos[i].title_name = xe::to_utf8(
              header->content_metadata.display_name(XLanguage::kEnglish));

          if (header->content_metadata.title_thumbnail_size > 0 &&
              header->content_metadata.title_thumbnail_size <=
                  vfs::XContentMetadata::kThumbLengthV1) {
            source_infos[i].icon_data.assign(
                header->content_metadata.title_thumbnail,
                header->content_metadata.title_thumbnail +
                    header->content_metadata.title_thumbnail_size);
          }
        }
      }
    }
  }

  std::string default_name = content_dirs.front().stem().string();
  if (content_dirs.size() == 1 && !source_infos[0].title_name.empty()) {
    default_name = source_infos[0].title_name;
  }

  if (content_dirs.size() == 1) {
    file_picker->set_mode(ui::FilePicker::Mode::kSave);
    file_picker->set_type(ui::FilePicker::Type::kFile);
    file_picker->set_multi_selection(false);
    file_picker->set_file_name(default_name);
    file_picker->set_default_extension("zar");
    file_picker->set_title("Zarchive File");
    file_picker->set_extensions({
        {"Zarchive File (*.zar)", "*.zar"},
    });
  } else {
    file_picker->set_title("Output Directory");
  }

  if (file_picker->Show(window_.get())) {
    zarchive_dir = file_picker->selected_files().front();
  }

  if (zarchive_dir.empty()) {
    return;
  }

  auto zarchive_entries =
      std::make_shared<std::vector<Emulator::ZarchiveEntry>>();

  for (size_t i = 0; i < content_dirs.size(); i++) {
    auto abs_content_dir = std::filesystem::absolute(content_dirs[i]);
    std::filesystem::path abs_zarchive_file;

    if (content_dirs.size() > 1) {
      std::string stem = !source_infos[i].title_name.empty()
                             ? source_infos[i].title_name
                             : abs_content_dir.stem().string();
      abs_zarchive_file = std::filesystem::absolute(
          (zarchive_dir / stem).replace_extension("zar"));
    } else {
      abs_zarchive_file = std::filesystem::absolute(zarchive_dir);
    }

    zarchive_entries->emplace_back(abs_content_dir, abs_zarchive_file,
                                   Emulator::ZarchiveOperation::Create);
    auto& entry = zarchive_entries->back();
    entry.name_ = xe::path_to_utf8(abs_zarchive_file.filename());
    entry.stfs_path_ = source_infos[i].stfs_path;
    entry.icon_data_ = std::move(source_infos[i].icon_data);
  }

  // Show dialog first, then start creation
  auto* dialog = new ui::ContentInstallDialogQt(nullptr, zarchive_entries);
  dialog->show();
  dialog->raise();
  dialog->activateWindow();

  auto createThread = std::thread([this, zarchive_entries] {
    for (auto& entry : *zarchive_entries) {
      emulator_->CreateZarchivePackage(entry);
    }
  });
  createThread.detach();
}

void EmulatorWindow::ShowContentDirectory() {
  auto content_root = emulator_->content_root();

  if (!std::filesystem::exists(content_root)) {
    std::filesystem::create_directories(content_root);
  }

  LaunchFileExplorer(content_root);
}

void EmulatorWindow::CpuTimeScalarReset() {
  Clock::set_guest_time_scalar(1.0);
  UpdateTitle();
}

void EmulatorWindow::CpuTimeScalarSetHalf() {
  Clock::set_guest_time_scalar(Clock::guest_time_scalar() / 2.0);
  UpdateTitle();
}

void EmulatorWindow::CpuTimeScalarSetDouble() {
  Clock::set_guest_time_scalar(Clock::guest_time_scalar() * 2.0);
  UpdateTitle();
}

void EmulatorWindow::CpuBreakIntoDebugger() {
  if (!cvars::debug) {
    xe::ui::ImGuiDialog::ShowMessageBox(imgui_drawer_.get(), "Xenia Debugger",
                                        "Xenia must be launched with the "
                                        "--debug flag in order to enable "
                                        "debugging.");
    return;
  }
  auto processor = emulator()->processor();
  if (processor->execution_state() == cpu::ExecutionState::kRunning) {
    // Currently running, so interrupt (and show the debugger).
    processor->Pause();
  } else {
    // Not running, so just bring the debugger into focus.
    processor->ShowDebugger();
  }
}

void EmulatorWindow::CpuBreakIntoHostDebugger() { xe::debugging::Break(); }

void EmulatorWindow::GpuTraceFrame() {
  emulator()->graphics_system()->RequestFrameTrace();
}

void EmulatorWindow::GpuClearCaches() {
  auto graphics_system = emulator()->graphics_system();
  graphics_system->ClearCaches();
  graphics_system->InvalidateGpuMemory();

  graphics_system->command_processor()->CallInThread([graphics_system]() {
    graphics_system->command_processor()->ClearReadbackBuffers();
  });
}

void EmulatorWindow::SetFullscreen(bool fullscreen) {
  if (window_->IsFullscreen() == fullscreen) {
    return;
  }
  window_->SetFullscreen(fullscreen);
}

void EmulatorWindow::ToggleFullscreen() {
  SetFullscreen(!window_->IsFullscreen());
}

void EmulatorWindow::ToggleDisplayConfigDialog() {
  if (postprocessing_dialog_) {
    postprocessing_dialog_->CloseDialog();
    postprocessing_dialog_ = nullptr;
    return;
  }

  postprocessing_dialog_ = new ui::ImGuiPostProcessingDialog(
      imgui_drawer(), this, emulator()->input_system());
  postprocessing_dialog_->SetOnCloseCallback(
      [this]() { postprocessing_dialog_ = nullptr; });
}

void EmulatorWindow::TogglePerformanceTuningDialog() {
  if (performance_dialog_) {
    performance_dialog_->CloseDialog();
    performance_dialog_ = nullptr;
    return;
  }

  performance_dialog_ = new ui::ImGuiPerformanceDialog(
      imgui_drawer(), this, emulator()->input_system());
  performance_dialog_->SetOnCloseCallback(
      [this]() { performance_dialog_ = nullptr; });
}

void EmulatorWindow::ToggleProfilesConfigDialog() {
  if (profile_dialog_) {
    profile_dialog_->CloseDialog();
    return;
  }

  profile_dialog_ =
      new ProfileConfigDialog(imgui_drawer(), this, emulator()->input_system());
  profile_dialog_->SetOnCloseCallback([this]() {
    profile_dialog_ = nullptr;
    // Refresh game list icons when profile dialog closes
    if (game_list_dialog_qt_) {
      game_list_dialog_qt_->RefreshIcons();
    }
  });
}

void EmulatorWindow::ToggleConfigDialog() {
  if (!simple_config_dialog_qt_) {
    simple_config_dialog_qt_ = new SimpleConfigDialogQt(nullptr, this);
  } else {
    simple_config_dialog_qt_->ReloadConfigValues();
  }

  simple_config_dialog_qt_->show();
  simple_config_dialog_qt_->raise();
  simple_config_dialog_qt_->activateWindow();
}

void EmulatorWindow::OpenConfigDialog(const std::string& category) {
  if (!config_dialog_qt_) {
    config_dialog_qt_ = new ConfigDialogQt(nullptr, this);
  }

  if (!category.empty()) {
    config_dialog_qt_->SelectCategory(category);
  }

  config_dialog_qt_->show();
  config_dialog_qt_->raise();
  config_dialog_qt_->activateWindow();
}

void EmulatorWindow::ToggleXMPConfigDialog() {
  if (xmp_dialog_) {
    xmp_dialog_->CloseDialog();
    xmp_dialog_ = nullptr;
    return;
  }

  xmp_dialog_ =
      new ui::ImGuiXmpDialog(imgui_drawer(), this, emulator()->input_system());
  xmp_dialog_->SetOnCloseCallback([this]() { xmp_dialog_ = nullptr; });
}

void EmulatorWindow::ToggleControllerVibration() {
  auto input_sys = emulator()->input_system();
  if (input_sys) {
    auto input_lock = input_sys->lock();

    input_sys->ToggleVibration();

    if (emulator_->kernel_state()) {
      emulator_->kernel_state()->BroadcastNotification(
          kXNotificationSystemProfileSettingChanged,
          static_cast<uint32_t>(input_sys->GetConnectedSlots().count()));
    }

    // Save the config to disk
    config::SaveConfig();

    // Show notification
    bool vibration_enabled = input_sys->GetVibrationCvar();
    std::string status = vibration_enabled ? "On" : "Off";

    app_context_.CallInUIThread([this, status]() {
      if (imgui_drawer()) {
        new ui::HostNotificationWindow(
            imgui_drawer(), "Controller Vibration",
            fmt::format("Vibration is now {}", status), 0);
      }
    });
  }
}

void EmulatorWindow::ShowCompatibility() {
  const std::string_view base_url =
      "https://github.com/xenia-canary/game-compatibility/issues";
  std::string url;
  // Avoid searching for a title ID of "00000000".
  uint32_t title_id = emulator_->title_id();
  if (!title_id) {
    url = base_url;
  } else {
    url = fmt::format("{}?q=is%3Aissue+is%3Aopen+{:08X}", base_url, title_id);
  }
  LaunchWebBrowser(url);
}

void EmulatorWindow::ShowFAQ() {
  LaunchWebBrowser("https://github.com/xenia-canary/xenia-canary/wiki/FAQ");
}

void EmulatorWindow::ShowBuildCommit() {
#ifdef XE_BUILD_IS_PR
  LaunchWebBrowser(
      "https://github.com/has207/xenia-edge/pull/" XE_BUILD_PR_NUMBER);
#else
  LaunchWebBrowser(
      "https://github.com/has207/xenia-edge/commit/" XE_BUILD_COMMIT);
#endif
}

void EmulatorWindow::ShowAbout() {
  auto* qt_window = dynamic_cast<ui::QtWindow*>(window_.get());
  if (!qt_window) {
    return;
  }

  QString about_text = QString(
                           "<h2>Xenia Edge</h2>"
                           "<p>Experimental fork of Xenia Canary</p>"
                           "<p><b>Branch:</b> %1<br>"
                           "<b>Commit:</b> %2<br>"
                           "<b>Build Date:</b> %3<br>"
                           "<b>Qt Version:</b> %4</p>"
                           "<p>For more information, visit <a "
                           "href=\"https://github.com/has207/"
                           "xenia-edge\">github.com/has207/xenia-edge</a></p>"
                           "<p><small>Icons by <a "
                           "href=\"https://icons8.com\">Icons8</a></small></p>")
                           .arg(XE_BUILD_BRANCH)
                           .arg(XE_BUILD_COMMIT_SHORT)
                           .arg(XE_BUILD_DATE)
                           .arg(qVersion());

  QMessageBox about_box(qt_window->qwindow());
  about_box.setWindowTitle("About Xenia Edge");
  about_box.setTextFormat(Qt::RichText);
  about_box.setText(about_text);
  about_box.setStandardButtons(QMessageBox::Ok);
  about_box.setDefaultButton(QMessageBox::Ok);

  // Ensure dialog sizes to fit all content
  QGridLayout* layout = qobject_cast<QGridLayout*>(about_box.layout());
  if (layout) {
    layout->setSizeConstraint(QLayout::SetMinimumSize);
  }

  about_box.exec();
}

void EmulatorWindow::UpdateTitle() {
  xe::StringBuffer sb;
  sb.Append(base_title_);

  // Title information, if available
  if (emulator()->is_title_open()) {
    sb.AppendFormat(" | [{:08X}", emulator()->title_id());
    auto title_version = emulator()->title_version();
    if (!title_version.empty()) {
      sb.Append(" v");
      sb.Append(title_version);
    }

    // Show disc number for multi-disc titles and non-default XEX name
    auto executable_module = emulator()->kernel_state()->GetExecutableModule();
    if (executable_module) {
      if (executable_module->is_multi_disc_title()) {
        // Use swapped disc number if set, otherwise use XEX header value
        uint8_t disc_number = swapped_disc_number_ != 0
                                  ? swapped_disc_number_
                                  : executable_module->disc_number();
        sb.AppendFormat(" Disc {}", disc_number);
      }

      // Show XEX name if it's not default.xex
      auto module_name = executable_module->name();
      auto module_name_lower = xe::utf8::lower_ascii(module_name);
      if (!module_name.empty() && module_name_lower != "default") {
        sb.Append(" ");
        sb.Append(module_name);
      }
    }

    sb.Append("]");

    auto title_name = emulator()->title_name();
    if (!title_name.empty()) {
      sb.Append(" ");
      sb.Append(title_name);
    }
  }

  // Graphics system name, if available
  auto graphics_system = emulator()->graphics_system();
  if (graphics_system) {
    auto graphics_name = graphics_system->name();
    if (!graphics_name.empty()) {
      sb.Append(" <");
      sb.Append(graphics_name);
      sb.Append(">");
    }
  }

  if (Clock::guest_time_scalar() != 1.0) {
    sb.AppendFormat(" (@{:.2f}x)", Clock::guest_time_scalar());
  }

  if (initializing_shader_storage_) {
    sb.Append(" (Preloading shaders\u2026)");
  }

  patcher::Patcher* patcher = emulator()->patcher();
  if (patcher && patcher->IsAnyPatchApplied()) {
    sb.Append(" [Patches Applied]");
  }

  patcher::PluginLoader* pluginloader = emulator()->plugin_loader();
  if (pluginloader && pluginloader->IsAnyPluginLoaded()) {
    sb.Append(" [Plugins Loaded]");
  }

  window_->SetTitle(sb.to_string_view());
}

void EmulatorWindow::SetInitializingShaderStorage(bool initializing) {
  if (initializing_shader_storage_ == initializing) {
    return;
  }
  initializing_shader_storage_ = initializing;
  UpdateTitle();
}

// Notes:
// SDL and XInput both support the guide button
//
// Assumes titles do not use the guide button.
// For titles that do such as dashboards these titles could be excluded based on
// their title ID.
//
// Xbox Gamebar:
// If the Xbox Gamebar overlay is enabled Windows will consume the guide
// button's input, this can be seen using hid-demo.
//
// Workaround: Detect if the Xbox Gamebar overlay is enabled then use the BACK
// button instead of the GUIDE button. Therefore BACK and GUIDE are reserved
// buttons for hotkeys.
//
// This is not an issue with DualShock controllers because Windows will not
// open the gamebar overlay using the PlayStation menu button.
//
// Xbox One S Controller:
// The guide button on this controller is very buggy no idea why.
// Using xinput usually registers after a double tap.
// Doesn't work at all using SDL.
// Needs more testing.
//
// Steam:
// If guide button focus is enabled steam will open.
// Steam uses BACK + GUIDE to open an On-Screen keyboard, however this is not a
// problem since both these buttons are reserved.
const std::map<int, EmulatorWindow::ControllerHotKey> controller_hotkey_map = {
    // Must use the Guide Button for all pass through hotkeys
    {X_INPUT_GAMEPAD_A | X_INPUT_GAMEPAD_GUIDE,
     EmulatorWindow::ControllerHotKey(
         EmulatorWindow::ButtonFunctions::ReadbackResolve,
         "A + Guide = Toggle Readback Resolve", true)},
    {X_INPUT_GAMEPAD_B | X_INPUT_GAMEPAD_GUIDE,
     EmulatorWindow::ControllerHotKey(
         EmulatorWindow::ButtonFunctions::ToggleLogging,
         "B + Guide = Toggle between loglevel set in config and the 'Disabled' "
         "loglevel.",
         true, true)},
    {X_INPUT_GAMEPAD_Y | X_INPUT_GAMEPAD_GUIDE,
     EmulatorWindow::ControllerHotKey(
         EmulatorWindow::ButtonFunctions::ToggleFullscreen,
         "Y + Guide = Toggle Fullscreen", true)},
    {X_INPUT_GAMEPAD_X | X_INPUT_GAMEPAD_GUIDE,
     EmulatorWindow::ControllerHotKey(
         EmulatorWindow::ButtonFunctions::ClearMemoryPageState,
         "X + Guide = Toggle Clear Memory Page State", true)},

    {X_INPUT_GAMEPAD_RIGHT_SHOULDER | X_INPUT_GAMEPAD_GUIDE,
     EmulatorWindow::ControllerHotKey(
         EmulatorWindow::ButtonFunctions::ClearGPUCache,
         "Right Shoulder + Guide = Clear GPU Cache", true)},
    {X_INPUT_GAMEPAD_LEFT_SHOULDER | X_INPUT_GAMEPAD_GUIDE,
     EmulatorWindow::ControllerHotKey(
         EmulatorWindow::ButtonFunctions::ToggleControllerVibration,
         "Left Shoulder + Guide = Toggle Controller Vibration", true)},

    // CPU Time Scalar with no rumble feedback
    {X_INPUT_GAMEPAD_DPAD_DOWN | X_INPUT_GAMEPAD_GUIDE,
     EmulatorWindow::ControllerHotKey(
         EmulatorWindow::ButtonFunctions::CpuTimeScalarSetHalf,
         "D-PAD Down + Guide = Half CPU Scalar")},
    {X_INPUT_GAMEPAD_DPAD_UP | X_INPUT_GAMEPAD_GUIDE,
     EmulatorWindow::ControllerHotKey(
         EmulatorWindow::ButtonFunctions::CpuTimeScalarSetDouble,
         "D-PAD Up + Guide = Double CPU Scalar")},
    {X_INPUT_GAMEPAD_DPAD_RIGHT | X_INPUT_GAMEPAD_GUIDE,
     EmulatorWindow::ControllerHotKey(
         EmulatorWindow::ButtonFunctions::CpuTimeScalarReset,
         "D-PAD Right + Guide = Reset CPU Scalar")},

    // non-pass through hotkeys
    {X_INPUT_GAMEPAD_Y, EmulatorWindow::ControllerHotKey(
                            EmulatorWindow::ButtonFunctions::ToggleFullscreen,
                            "Y = Toggle Fullscreen", true, false)},
    {X_INPUT_GAMEPAD_BACK | X_INPUT_GAMEPAD_START,
     EmulatorWindow::ControllerHotKey(
         EmulatorWindow::ButtonFunctions::ToggleLogging,
         "Back + Start = Toggle between loglevel set in config and the "
         "'Disabled' loglevel.",
         false, false)}};

EmulatorWindow::ControllerHotKey EmulatorWindow::ProcessControllerHotkey(
    int buttons) {
  // Default return value
  EmulatorWindow::ControllerHotKey Unknown_hotkey = {};

  // Track guide button state for edge detection (must be before early return)
  static bool prev_guide_pressed = false;

  if (buttons == 0) {
    prev_guide_pressed = false;
    return Unknown_hotkey;
  }

  if (disable_hotkeys_.load()) {
    return Unknown_hotkey;
  }

  // Hotkey cool-down to prevent toggling too fast
  constexpr std::chrono::milliseconds delay(75);

  // If the Xbox Gamebar is enabled or the Guide button is disabled then
  // replace the Guide button with the Back button without redeclaring the key
  // mappings
  if (IsUseNexusForGameBarEnabled() || !cvars::guide_button) {
    if ((buttons & X_INPUT_GAMEPAD_BACK) == X_INPUT_GAMEPAD_BACK) {
      buttons &= ~X_INPUT_GAMEPAD_BACK;
      buttons |= X_INPUT_GAMEPAD_GUIDE;
    }
  }

  // When controller_hotkeys is disabled, use guide button alone to toggle
  // context menu (with edge detection to prevent repeated toggling)
  if (!cvars::controller_hotkeys) {
    bool guide_pressed = (buttons == X_INPUT_GAMEPAD_GUIDE);

    if (guide_pressed && !prev_guide_pressed) {
      app_context().CallInUIThread([this]() { ToggleContextMenu(false); });
      prev_guide_pressed = true;
      return Unknown_hotkey;
    }
    prev_guide_pressed = guide_pressed;
  }

  auto it = controller_hotkey_map.find(buttons);
  if (it == controller_hotkey_map.end()) {
    return Unknown_hotkey;
  }

  // Do not activate hotkeys that are not intended for activation during
  // gameplay
  if (emulator_->is_title_open()) {
    // If non-pass through (menu hoykeys) or hotkeys disabled then return
    if (!it->second.title_passthru || !cvars::controller_hotkeys) {
      return Unknown_hotkey;
    }
  }

  std::string notificationTitle = "";
  std::string notificationDesc = "";

  EmulatorWindow::ControllerHotKey button_combination = it->second;

  switch (button_combination.function) {
    case ButtonFunctions::ToggleFullscreen:
      app_context().CallInUIThread([this]() { ToggleFullscreen(); });

      // Extra Sleep
      xe::threading::Sleep(delay);
      break;
    case ButtonFunctions::ClearMemoryPageState:
      ToggleGPUSetting(GPUSetting::ClearMemoryPageState);

      // Assume the user wants ClearCaches as well
      if (cvars::clear_memory_page_state) {
        GpuClearCaches();
      }

      notificationTitle = "Toggle Clear Memory Page State";
      notificationDesc =
          cvars::clear_memory_page_state ? "Enabled" : "Disabled";

      // Extra Sleep
      xe::threading::Sleep(delay);
      break;
    case ButtonFunctions::ReadbackResolve:
      CycleReadbackResolve();

      notificationTitle = "Readback Resolve Mode";
      notificationDesc = cvars::readback_resolve;

      // Extra Sleep
      xe::threading::Sleep(delay);
      break;
    case ButtonFunctions::CpuTimeScalarSetHalf:
      CpuTimeScalarSetHalf();

      notificationTitle = "Time Scalar";
      notificationDesc =
          fmt::format("Decreased to {}", Clock::guest_time_scalar());
      break;
    case ButtonFunctions::CpuTimeScalarSetDouble:
      CpuTimeScalarSetDouble();

      notificationTitle = "Time Scalar";
      notificationDesc =
          fmt::format("Increased to {}", Clock::guest_time_scalar());
      break;
    case ButtonFunctions::CpuTimeScalarReset:
      CpuTimeScalarReset();

      notificationTitle = "Time Scalar";
      notificationDesc = fmt::format("Reset to {}", Clock::guest_time_scalar());
      break;
    case ButtonFunctions::ClearGPUCache:
      GpuClearCaches();

      notificationTitle = "Clear GPU Cache";
      notificationDesc = "Complete";

      // Extra Sleep
      xe::threading::Sleep(delay);
      break;
    case ButtonFunctions::ToggleControllerVibration: {
      ToggleControllerVibration();

      bool vibration = false;

      auto input_sys = emulator()->input_system();
      if (input_sys) {
        vibration = input_sys->GetVibrationCvar();
      }

      notificationTitle = "Toggle Controller Vibration";
      notificationDesc = vibration ? "Enabled" : "Disabled";

      // Extra Sleep
      xe::threading::Sleep(delay);
    } break;
    case ButtonFunctions::ToggleLogging: {
      logging::ToggleLogLevel();

      notificationTitle = "Toggle Logging";

      LogLevel level = static_cast<LogLevel>(logging::internal::GetLogLevel());
      notificationDesc = level == LogLevel::Disabled ? "Disabled" : "Enabled";
    } break;
    case ButtonFunctions::Unknown:
    default:
      break;
  }

  if (!notificationTitle.empty()) {
    app_context_.CallInUIThread([this, notificationTitle, notificationDesc]() {
      if (imgui_drawer()) {
        new ui::HostNotificationWindow(imgui_drawer(), notificationTitle,
                                       notificationDesc, 0);
      }
    });
  }

  xe::threading::Sleep(delay);

  return it->second;
}

void EmulatorWindow::VibrateController(xe::hid::InputSystem* input_sys,
                                       uint32_t user_index,
                                       bool toggle_rumble) {
  constexpr std::chrono::milliseconds rumble_duration(100);

  // Hold lock while sleeping this thread for the duration of the rumble,
  // otherwise the rumble may fail.
  auto input_lock = input_sys->lock();

  X_INPUT_VIBRATION vibration = {};

  vibration.left_motor_speed = toggle_rumble ? UINT16_MAX : 0;
  vibration.right_motor_speed = toggle_rumble ? UINT16_MAX : 0;

  input_sys->SetState(user_index, &vibration);

  // Vibration duration
  if (toggle_rumble) {
    xe::threading::Sleep(rumble_duration);
  }
}

void EmulatorWindow::GamepadHotKeys() {
  X_INPUT_STATE state;

  constexpr std::chrono::milliseconds thread_delay(75);

  auto input_sys = emulator_->input_system();

  if (input_sys) {
    while (true) {
      // Collect controller states while holding the lock
      std::array<std::pair<bool, X_INPUT_STATE>, XUserMaxUserCount>
          controller_states;
      {
        auto input_lock = input_sys->lock();
        for (uint32_t user_index = 0; user_index < XUserMaxUserCount;
             ++user_index) {
          X_RESULT result = input_sys->GetState(
              user_index, X_INPUT_FLAG::X_INPUT_FLAG_GAMEPAD, &state);
          controller_states[user_index] = {result == X_ERROR_SUCCESS, state};
        }
      }  // Lock is released here when input_lock goes out of scope

      // Process hotkeys without holding the lock
      for (uint32_t user_index = 0; user_index < XUserMaxUserCount;
           ++user_index) {
        if (controller_states[user_index].first) {
          if (ProcessControllerHotkey(
                  controller_states[user_index].second.gamepad.buttons)
                  .rumble) {
            // Enable Vibration
            VibrateController(input_sys, user_index, true);

            // Disable Vibration
            VibrateController(input_sys, user_index, false);
          }
        }
      }

      xe::threading::Sleep(thread_delay);
    }
  }
}

void EmulatorWindow::ToggleGPUSetting(gpu::GPUSetting setting) {
  const char* cvar_name = nullptr;
  bool new_value = false;

  switch (setting) {
    case GPUSetting::ClearMemoryPageState:
      new_value = !cvars::clear_memory_page_state;
      SaveGPUSetting(GPUSetting::ClearMemoryPageState, new_value);
      cvar_name = "clear_memory_page_state";
      break;
    case GPUSetting::ReadbackMemexport:
      new_value = !cvars::readback_memexport;
      SaveGPUSetting(GPUSetting::ReadbackMemexport, new_value);
      cvar_name = "readback_memexport";
      break;
  }

  // Save to per-game config if a title is loaded
  if (cvar_name && emulator_ && emulator_->is_title_open()) {
    uint32_t title_id = emulator_->title_id();
    if (title_id != 0) {
      toml::table config_table = config::LoadGameConfig(title_id);

      if (!config_table.contains("GPU")) {
        config_table.insert("GPU", toml::table{});
      }

      auto* gpu_table = config_table["GPU"].as_table();
      if (gpu_table) {
        gpu_table->insert_or_assign(cvar_name, new_value);
      }

      config::SaveGameConfig(title_id, config_table);
    }
  }
}

void EmulatorWindow::CycleReadbackResolve() {
  auto* graphics_system = emulator_->graphics_system();
  if (!graphics_system) return;
  auto* command_processor = graphics_system->command_processor();
  if (!command_processor) return;

  gpu::ReadbackResolveMode current =
      command_processor->GetReadbackResolveMode();
  gpu::ReadbackResolveMode next;
  switch (current) {
    case gpu::ReadbackResolveMode::kDisabled:
      next = gpu::ReadbackResolveMode::kSome;
      break;
    case gpu::ReadbackResolveMode::kSome:
      next = gpu::ReadbackResolveMode::kFast;
      break;
    case gpu::ReadbackResolveMode::kFast:
      next = gpu::ReadbackResolveMode::kFull;
      break;
    default:
      next = gpu::ReadbackResolveMode::kDisabled;
      break;
  }
  command_processor->SetReadbackResolveMode(next);
}

std::string EmulatorWindow::CanonicalizeFileExtension(
    const std::filesystem::path& path) {
  return xe::utf8::lower_ascii(xe::path_to_utf8(path.extension()));
}

void EmulatorWindow::LaunchTitleInNewProcess(
    const std::filesystem::path& path_to_file) {
  // Get the path to the current executable
  std::filesystem::path executable_path = xe::filesystem::GetExecutablePath();

  // Verify the file exists
  if (!path_to_file.empty() && !std::filesystem::exists(path_to_file)) {
    XELOGE("Cannot launch title - file not found: {}", path_to_file.string());
    return;
  }

#if XE_PLATFORM_WIN32
  // On Windows, build command line using Xenia's Unicode path handling
  auto exe_path_u16 = xe::path_to_utf16(executable_path);

  // Build full command line with quotes for paths that may contain spaces
  std::u16string cmd_line = u"\"" + exe_path_u16 + u"\"";

  // Pass the config file path if one is being used
  if (!cvars::config.empty()) {
    cmd_line += u" --config=\"" + xe::to_utf16(cvars::config) + u"\"";
  }

  // Tell game process to return to UI when it exits
  cmd_line += u" --return_to_ui=true";

  // Add the target game file
  if (!path_to_file.empty()) {
    auto game_path_u16 = xe::path_to_utf16(path_to_file);
    cmd_line += u" \"" + game_path_u16 + u"\"";
  }

  STARTUPINFOW si = {};
  si.cb = sizeof(si);
  PROCESS_INFORMATION pi = {};

  if (!CreateProcessW(nullptr,  // Application name (use command line)
                      const_cast<wchar_t*>(reinterpret_cast<const wchar_t*>(
                          cmd_line.c_str())),  // Command line
                      nullptr,                 // Process attributes
                      nullptr,                 // Thread attributes
                      FALSE,                   // Inherit handles
                      CREATE_NEW_CONSOLE,      // Creation flags
                      nullptr,                 // Environment
                      nullptr,                 // Current directory
                      &si,                     // Startup info
                      &pi)) {                  // Process information
    XELOGE("Failed to launch new process: {}", GetLastError());
    return;
  }

  // Allow the new process to bring itself to the foreground
  AllowSetForegroundWindow(pi.dwProcessId);
  CloseHandle(pi.hProcess);
  CloseHandle(pi.hThread);
#else
  // On Linux/Unix, use fork/exec for proper process creation
  pid_t pid = fork();

  if (pid == 0) {
    // Child process

#if XE_PLATFORM_LINUX
    // Set MangoHUD environment variable if enabled
    if (cvars::use_mangohud) {
      setenv("MANGOHUD", "1", 1);
    }
#endif  // XE_PLATFORM_LINUX

    std::vector<const char*> argv;
#if XE_PLATFORM_LINUX
    std::string gamemode_cmd;

    // If GameMode is enabled, use gamemoderun as the executable
    if (cvars::use_gamemode) {
      gamemode_cmd = "gamemoderun";
      argv.push_back(gamemode_cmd.c_str());
      argv.push_back(executable_path.c_str());
    } else {
      argv.push_back(executable_path.c_str());
    }
#else
    argv.push_back(executable_path.c_str());
#endif  // XE_PLATFORM_LINUX

    // Pass the config file if one is being used
    std::string config_arg;
    if (!cvars::config.empty()) {
      config_arg = "--config=" + cvars::config;
      argv.push_back(config_arg.c_str());
    }

    // Tell game process to return to UI when it exits
    argv.push_back("--return_to_ui=true");

    // Add the target game file
    std::string target_arg;
    if (!path_to_file.empty()) {
      target_arg = path_to_file.string();
      argv.push_back(target_arg.c_str());
    }
    argv.push_back(nullptr);

    // Execute the new process
#if XE_PLATFORM_LINUX
    if (cvars::use_gamemode) {
      // Use execvp to search PATH for gamemoderun
      execvp(gamemode_cmd.c_str(), const_cast<char**>(argv.data()));
    } else {
      execv(executable_path.c_str(), const_cast<char**>(argv.data()));
    }
    // If exec returns, it failed
    XELOGE("Failed to execute: {}",
           cvars::use_gamemode ? gamemode_cmd : executable_path.string());
#else
    execv(executable_path.c_str(), const_cast<char**>(argv.data()));
    // If exec returns, it failed
    XELOGE("Failed to execute: {}", executable_path.string());
#endif  // XE_PLATFORM_LINUX
    std::exit(1);
  } else if (pid < 0) {
    // Fork failed
    XELOGE("Failed to fork process");
    return;
  }
#endif

  XELOGI("Launched title in new process: {}", path_to_file.string());

  // Exit UI process - game process will spawn new UI when it exits
  xe::FlushLog();
  app_context_.QuitFromUIThread();
}

xe::X_STATUS EmulatorWindow::RunTitle(
    const std::filesystem::path& path_to_file) {
  std::error_code ec = {};
  bool titleExists = std::filesystem::exists(path_to_file, ec);

  if (path_to_file.empty() || !titleExists) {
    std::string log_msg =
        fmt::format("Failed to launch title path is {}.",
                    path_to_file.empty() ? "empty" : "invalid");

    if (!path_to_file.empty() && !titleExists) {
      log_msg.append(fmt::format("\nProvided Path: {}", path_to_file));
    }

    if (ec) {
      log_msg.append(fmt::format("\nExtended message info: {} ({:08X})",
                                 ec.message(), ec.value()));
    }

    XELOGE("{}", log_msg);

    ClearDialogs();

    xe::ui::ImGuiDialog::ShowMessageBox(imgui_drawer_.get(),
                                        "Title Launch Failed!", log_msg);

    return X_STATUS_NO_SUCH_FILE;
  }

  if (emulator_->is_title_open()) {
    // Terminate the current title and start a new title.
    // if (emulator_->TerminateTitle() == X_STATUS_SUCCESS) {
    //   return RunTitle(path);
    // }

    return X_STATUS_UNSUCCESSFUL;
  }

  // Prevent crashing the emulator by not loading a game if a game is already
  // loaded.
  auto abs_path = std::filesystem::absolute(path_to_file);

  auto extension = CanonicalizeFileExtension(abs_path);

  if (extension == ".7z" || extension == ".zip" || extension == ".rar" ||
      extension == ".tar" || extension == ".gz") {
    xe::ShowSimpleMessageBox(
        xe::SimpleMessageBoxType::Error,
        fmt::format(
            "Unsupported format!\n"
            "Xenia does not support running software in an archived format."));

    return X_STATUS_UNSUCCESSFUL;
  }

  auto result = emulator_->LaunchPath(abs_path);

  disable_hotkeys_ = false;

  ClearDialogs();

  if (result) {
    XELOGE("Failed to launch target: {:08X}", result);

    xe::ui::ImGuiDialog::ShowMessageBox(
        imgui_drawer_.get(), "Title Launch Failed!",
        "Failed to launch title.\n\nCheck xenia.log for technical details.");

    emulator_->file_system()->Clear();
  } else {
    auto xam =
        emulator_->kernel_state()->GetKernelModule<kernel::xam::XamModule>(
            "xam.xex");

    xam->loader_data().host_path = xe::path_to_utf8(abs_path);
  }

  return result;
}

std::filesystem::path EmulatorWindow::GetFilePickerInitialDirectory() const {
  auto kernel_state = emulator_->kernel_state();
  if (!kernel_state) {
    return {};
  }

  auto xam_state = kernel_state->xam_state();
  if (!xam_state) {
    return {};
  }

  auto profile_manager = xam_state->profile_manager();
  if (!profile_manager) {
    return {};
  }

  auto recent_path = profile_manager->GetMostRecentlyPlayedTitlePath();
  if (!recent_path.empty() && std::filesystem::exists(recent_path)) {
    auto parent_dir = recent_path.parent_path();
    if (!parent_dir.empty() && std::filesystem::exists(parent_dir)) {
      return parent_dir;
    }
  }

  return {};
}

void EmulatorWindow::ClearDialogs() {
  if (postprocessing_dialog_) {
    postprocessing_dialog_->CloseDialog();
    postprocessing_dialog_ = nullptr;
  }
  if (performance_dialog_) {
    performance_dialog_->CloseDialog();
    performance_dialog_ = nullptr;
  }
  if (xmp_dialog_) {
    xmp_dialog_->CloseDialog();
    xmp_dialog_ = nullptr;
  }
  if (profile_dialog_) {
    profile_dialog_->CloseDialog();
    profile_dialog_ = nullptr;
  }

  imgui_drawer_.get()->ClearDialogs();
  emulator_->kernel_state()->xam_state()->xam_dialogs_shown_ = 0;
}

}  // namespace app
}  // namespace xe
